### ISSUE TITLE
why did you move from fastpages to substack?

### ISSUE THREAD

**Issue by akvsak** [jwuphysics/blog#9]
Just curious. I'm also looking to start a blog about data science.

1) Given that most of your work is based on code and python notebooks, would it not be better to use fastpages auto-rendering notebooks into blog posts?

2) What would be the advantages of substack over fastpages+github pages hosting for a scientific or technical blog?

Thanks.

p.s. I thought this might be the best place to ask this question.

**Comment by jwuphysics** [comment]
Good question @akvsak, I've thought about this too. I was using an early version of fastpages and rather than break my blog by updating, I decided to break it by migrating to Substack. I was also constantly getting flagged by dependabot for various security vulnerabilities, which I found annoying. Ultimately I'm not sure whether that was a good or bad decision  to migrate!

With Substack it's easier for me to focus on writing, which I thought was more important than providing inline code (since the code exists in various repositories anyway). However, you obviously have less control than if you host your own blog on Github pages. If I had made my blog later, I probably would have used [academicpages](https://academicpages.github.io/). In any event, I think that it's more important to find a good-enough platform and just keep writing!

**Comment by akvsak** [comment]
> Good question @akvsak, I've thought about this too. I was using an early version of fastpages and rather than break my blog by updating, I decided to break it by migrating to Substack. I was also constantly getting flagged by dependabot for various security vulnerabilities, which I found annoying. Ultimately I'm not sure whether that was a good or bad decision to migrate!
> 
> With Substack it's easier for me to focus on writing, which I thought was more important than providing inline code (since the code exists in various repositories anyway). However, you obviously have less control than if you host your own blog on Github pages. If I had made my blog later, I probably would have used [academicpages](https://academicpages.github.io/). In any event, I think that it's more important to find a good-enough platform and just keep writing!

Ah. Ok. Got it. I didn't anticipate that GH build system might get cumbersome. 

I was imagining that with fastpages, I can write a MS Word Doc and ipynb and have it instantly rendered web ready with equations, syntax especially without worrying about manual conversion, link generation and HTML formatting.

I will try out your recommendations. Thanks for answering.

Also your blog content is insightful and inspiring about how algorithms are changing the way science is being assisted by technology.

**Comment by jwuphysics** [comment]
Glad to hear it, and thank you!
